name: Deploy React App from main

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout automático da branch que disparou o workflow (main)
      - uses: actions/checkout@v3

      # Prepara ambiente Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instala dependências
      - name: Install dependencies
        run: npm ci

      # Gera o bundle estático em /dist
      - name: Build
        run: npm run build

      # Publica em gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
